/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32f051x8.h"
#include "motor_controller.h"
#include "chassis.h"
#include "Bluetooth_USART2.h"
#include "IR.h"

#define RX_BUF_SIZE 32
#define MAX_MENSAJE 20

IRSensor IR_MostOuterRight = { GPIOB, 9};
IRSensor IR_OuterRight = { GPIOB, 10};
IRSensor IR_CenterRight = { GPIOB, 11};
IRSensor IR_Center = { GPIOB, 12};
IRSensor IR_CenterLeft = { GPIOB, 13};
IRSensor IR_OuterLeft = { GPIOB, 14};
IRSensor IR_MostOuterLeft = { GPIOB, 15};

volatile bool emergencyStop = 0;
volatile int emergencyCounter = 0;

volatile bool sensorStates[7];

bool justEnteredLineMode;
bool lineFollowerMode = 0;
bool flag_Bluetooth_state = 1;

float forward_speed_LF = 0; // Choose based on desired speed (0.0 to 1.0)
float temp_P;
float temp_I;
float temp_D;

int main(void) {
	USART2_Init_Interrupt();
	System_Ready_Indicator();

	MotorController motorA;
	MotorController motorB;
	CHASSIS agv;

	// Initialize motor (Dir1, Dir2, PWM, BrakePin)
	Motor_Init(&motorA, 6, 7, 8, 5);
	Motor_Init(&motorB, 10, 11, 9, 4);
	Motor_Invert(&motorB, 1);
	Init_Chassis(&agv,motorA,motorB);

	LineFollower Follower = {IR_MostOuterRight, IR_OuterRight, IR_CenterRight, IR_Center, IR_CenterLeft, IR_OuterLeft, IR_MostOuterLeft};
	LineFollower_Init(&Follower);

   // Test sequence
    while (1) {

		if (!emergencyStop & flag_Bluetooth_state) {

			if (rx_ready == 1) {
				apply_CurrentSpeedsToMotors(&agv);
				USART2_HandleMessage(&agv);
			}

			if (lineFollowerMode == 1) {
				if (justEnteredLineMode) {
					SoftStart_Chassis(&agv, forward_speed_LF, 0.0, 500.0, 20.0);  // Ramp to 0.3 speed over 500ms
					justEnteredLineMode = false;
					delay_ms(500);
				}
				apply_CurrentSpeedsToMotors_noBrake_if_0(&agv);
				LineFollower_FollowLine(&Follower, &agv, forward_speed_LF);
			}
		} else {
			pause_Chassis(&agv);
		}
	}
}




